### ISSUE TITLE
The program doesn't work

### ISSUE THREAD

**Issue by koljan818** [maslovmk/3SEM-TASK#1]
[nick@arch_host LS]$ gcc test_maslov.c 
[nick@arch_host LS]$ ls
a.out  test_maslov.c  test_plotnik.c
[nick@arch_host LS]$ ./a.out /home/nick/
--------------------------------------------
File path:  /home/nick/Desktop
Statistics couldn't be taken.[nick@arch_host LS]$ pwd
/home/nick/students_works/3SEM-TASK/LS

**Comment by maslovmk** [comment]
Fixed
