### ISSUE TITLE
Useless doesn't work with this program >>

### ISSUE THREAD

**Issue by koljan818** [maslovmk/3SEM-TASK#2]
cat src.c
#include <stdio.h>
#include <string.h>
int main(int argc, char* argv[])
{
    if(!strcmp(argv[0], "ls"))
        printf("Running ls\n");
    if(!strcmp(argv[0], "pwd"))
        printf("Running pwd\n");
    return 0;
}

Should compile:
clang -o my_pwd src.c
clang -o my_ls src.c

cat input.txt:
5 /full/path/to/my_pwd
7 /full/path/to/my_ls

This should after 5 seconds print pwd, after 7 seconds print ls

**Comment by maslovmk** [comment]
What is after #include?

**Comment by maslovmk** [comment]
Fixed issue.
